/** In-app notification types. Plain storage — not a notification engine. */
export const NOTIFICATION_TYPES = {
  ACCOUNTABILITY_SUBMITTED: 'ACCOUNTABILITY_SUBMITTED',
  ACCOUNTABILITY_ASSIGNED: 'ACCOUNTABILITY_ASSIGNED',
  ACCOUNTABILITY_RETURNED: 'ACCOUNTABILITY_RETURNED',
  CLARIFICATION_REQUESTED: 'CLARIFICATION_REQUESTED',
  ACCOUNTABILITY_RESUBMITTED: 'ACCOUNTABILITY_RESUBMITTED',
  ACCOUNTABILITY_APPROVED: 'ACCOUNTABILITY_APPROVED',
  ACCOUNTABILITY_REJECTED: 'ACCOUNTABILITY_REJECTED',
  ACCOUNTABILITY_CLOSED: 'ACCOUNTABILITY_CLOSED',
  ACCOUNTABILITY_DUE_SOON: 'ACCOUNTABILITY_DUE_SOON',
  ACCOUNTABILITY_OVERDUE: 'ACCOUNTABILITY_OVERDUE',
  PARTICIPATION_EARLY_WARNING: 'PARTICIPATION_EARLY_WARNING',
  PARTICIPATION_THRESHOLD_REACHED: 'PARTICIPATION_THRESHOLD_REACHED',
  PARTICIPATION_EXCEEDED: 'PARTICIPATION_EXCEEDED',
  MONTHLY_LIMIT_EXCEEDED: 'MONTHLY_LIMIT_EXCEEDED',
  ACTIVITY_OVERLAP_REVIEW: 'ACTIVITY_OVERLAP_REVIEW',
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];

export type NotifyInput = {
  recipientUserId: string;
  type: NotificationType | string;
  title: string;
  message: string;
  referenceType?: string | null;
  referenceId?: string | null;
  href?: string | null;
  /** Stable key for deduplication within type+recipient. */
  dedupeKey: string;
};
